SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 15 
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5
PLAYER_IMAGE_PATH = "assets/player_images/spaceship1.png"
ASTEROID_IMAGE_PATH = "assets/asteroid_images/asteroid2.png"

SCORE_FONT_SIZE = 24
SCORE_COLOR = "white"
SCORE_POSITION = (20, 20)
HIGH_SCORE_FILE = "high_score.txt"
ASTEROID_SCORE_BASE = 10